FROM node:24-alpine3.21

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    CYPRESS_INSTALL_BINARY=0 HUSKY=0 pnpm install --frozen-lockfile --store-dir=/pnpm/store

COPY . .

RUN ["pnpm", "run", "build"]

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
