FROM node:24-alpine3.21

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm install --production && npm install typescript --save-dev

COPY . .

RUN ["npm", "run", "build"]

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]